# Generated by Django 5.2.9 on 2026-01-28 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0001_initial'),
        ('app_dashboard', '0003_vendorservice_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('event_date', models.DateField()),
                ('venue', models.CharField(max_length=255)),
                ('number_of_participants', models.PositiveIntegerField()),
                ('time', models.TimeField()),
                ('note', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app_dashboard.customer')),
            ],
        ),
    ]
