# Generated by Django 5.2.9 on 2026-01-29 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0003_booking_details'),
        ('app_dashboard', '0003_vendorservice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_service', to='app_dashboard.vendorservice'),
        ),
    ]
