# Generated by Django 5.2.9 on 2026-01-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0005_booking_master_grandtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_master',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
