# Generated by Django 5.2.9 on 2026-01-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0006_alter_booking_master_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_master',
            name='number_of_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
