# Generated by Django 5.2.9 on 2026-02-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0010_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
