# Generated by Django 5.2.9 on 2026-02-09 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0012_booking_master_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_master',
            name='vendor',
        ),
    ]
