# Generated by Django 5.2.9 on 2026-02-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0013_remove_booking_master_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_details',
            name='status',
            field=models.CharField(default='booked', max_length=100),
        ),
    ]
