# Generated by Django 5.2.9 on 2026-02-28 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0015_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
