# Generated by Django 5.2.9 on 2026-03-04 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0006_auditorium'),
        ('app_customer', '0016_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_master',
            name='auditorium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_core.auditorium'),
        ),
        migrations.AlterField(
            model_name='booking_master',
            name='venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
