# Generated by Django 5.2.9 on 2026-03-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0017_booking_master_auditorium_alter_booking_master_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_master',
            name='booking_type',
            field=models.CharField(blank=True, null=True),
        ),
    ]
