# Generated by Django 5.2.9 on 2026-02-24 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0014_booking_details_status'),
        ('app_vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='app_customer.booking_master')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_vendor.staff')),
            ],
        ),
    ]
