# Generated by Django 5.2.9 on 2026-01-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0002_alter_vendorservice_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorservice',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
