# Generated by Django 5.2.9 on 2026-02-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0003_vendorservice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorservice',
            name='duration',
            field=models.CharField(blank=True, null=True),
        ),
    ]
