# Generated by Django 5.2.9 on 2026-01-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.CharField()),
                ('image', models.ImageField(null=True, upload_to='media/')),
            ],
        ),
    ]
