# Generated by Django 5.2.9 on 2026-02-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0004_eventtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
