# Generated by Django 5.2.9 on 2026-03-04 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0005_alter_category_description_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('hours', models.CharField()),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.location')),
            ],
        ),
    ]
