# Generated by Django 5.2.9 on 2026-03-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0006_auditorium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorium',
            name='hours',
            field=models.IntegerField(),
        ),
    ]
