# Generated by Django 5.2.9 on 2026-03-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0007_alter_auditorium_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorium',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
