# Generated by Django 5.2.9 on 2026-03-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0008_auditorium_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorium',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
